name: Notim
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  rename: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.4"
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/ic_launcher.png"
  min_sdk_android: 21
flutter:
  uses-material-design: true

  assets:
    - assets/image/

  fonts:
    - family: vazir
      fonts:
        - asset: assets/fonts/Vazir_Bold.ttf
          weight: 700
        - asset: assets/fonts/Vazir_Medium.ttf
          weight: 400
        - asset: assets/fonts/Vazir_Light.ttf
          weight: 300
        - asset: assets/fonts/Vazir_Thin.ttf
          weight: 100
